### ISSUE TITLE
feat: close emoji picker on pressing <esc> and on clicking outside the picker

### ISSUE THREAD

**Issue by sumitst05** [sumitst05/PeerPod#5]
## Description:

The emoji picker of chat should get closed when clicked outside it or when `Escape` key is pressed.

## Current Behavior:

https://github.com/user-attachments/assets/28a98f09-13c9-42a6-b6f0-10665ccd7a86

- The emoji picker does not close on pressing `Escape` key or clicking outside the picker
- It closes only on clicking the emoji selector button

## Expected Behavior:

Clicking outside the picker or pressing `Escape` key should close the picker window

## Suggested solution:

- Use a state variable to manage the visibility of the emoji picker.
- Add an event listener for clicks outside the picker to update the visibility state.
- Add an event listener for the Escape key to close the picker.

**Comment by amitsuthar69** [comment]
[Screencast From 2024-10-20 18-55-36.webm](https://github.com/user-attachments/assets/af79d436-af52-4bec-9685-fc7d3e02825d)
